[package]
name = "example_guest"
version = "0.1.0"
authors = ["Alec Deason <wasm_plugins@tinycountry.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm_plugin_guest = { path = "../../guest" }
